export const cityOptions = [
  { label: "Anantapur", value: "Anantapur" },
  { label: "Chittoor", value: "Chittoor" },
  { label: "East Godavari", value: "East Godavari" },
  { label: "Guntur", value: "Guntur" },
  { label: "Kadapa", value: "Kadapa" },
  { label: "Krishna", value: "Krishna" },
  { label: "Kurnool", value: "Kurnool" },
  { label: "Nellore", value: "Nellore" },
  { label: "Prakasam", value: "Prakasam" },
  { label: "Srikakulam", value: "Srikakulam" },
  { label: "Visakhapatnam", value: "Visakhapatnam" },
  { label: "Vizianagaram", value: "Vizianagaram" },
  { label: "West Godavari", value: "West Godavari" },
  { label: "Tawang", value: "Tawang" },
  { label: "West Kameng", value: "West Kameng" },
  { label: "East Kameng", value: "East Kameng" },
  { label: "Papum Pare", value: "Papum Pare" },
  { label: "Kurung Kumey", value: "Kurung Kumey" },
  { label: "Kra Daadi", value: "Kra Daadi" },
  { label: "Lower Subansiri", value: "Lower Subansiri" },
  { label: "Upper Subansiri", value: "Upper Subansiri" },
  { label: "West Siang", value: "West Siang" },
  { label: "East Siang", value: "East Siang" },
  { label: "Siang", value: "Siang" },
  { label: "Upper Siang", value: "Upper Siang" },
  { label: "Lower Siang", value: "Lower Siang" },
  { label: "Lower Dibang Valley", value: "Lower Dibang Valley" },
  { label: "Dibang Valley", value: "Dibang Valley" },
  { label: "Anjaw", value: "Anjaw" },
  { label: "Lohit", value: "Lohit" },
  { label: "Namsai", value: "Namsai" },
  { label: "Changlang", value: "Changlang" },
  { label: "Tirap", value: "Tirap" },
  { label: "Longding", value: "Longding" },
  { label: "Baksa", value: "Baksa" },
  { label: "Barpeta", value: "Barpeta" },
  { label: "Biswanath", value: "Biswanath" },
  { label: "Bongaigaon", value: "Bongaigaon" },
  { label: "Cachar", value: "Cachar" },
  { label: "Charaideo", value: "Charaideo" },
  { label: "Chirang", value: "Chirang" },
  { label: "Darrang", value: "Darrang" },
  { label: "Dhemaji", value: "Dhemaji" },
  { label: "Dhubri", value: "Dhubri" },
  { label: "Dibrugarh", value: "Dibrugarh" },
  { label: "Dima Hasao", value: "Dima Hasao" },
  { label: "Goalpara", value: "Goalpara" },
  { label: "Golaghat", value: "Golaghat" },
  { label: "Hailakandi", value: "Hailakandi" },
  { label: "Hojai", value: "Hojai" },
  { label: "Jorhat", value: "Jorhat" },
  { label: "Kamrup", value: "Kamrup" },
  { label: "Kamrup Metropolitan", value: "Kamrup Metropolitan" },
  { label: "Karbi Anglong", value: "Karbi Anglong" },
  { label: "Karimganj", value: "Karimganj" },
  { label: "Kokrajhar", value: "Kokrajhar" },
  { label: "Lakhimpur", value: "Lakhimpur" },
  { label: "Majuli", value: "Majuli" },
  { label: "Morigaon", value: "Morigaon" },
  { label: "Nagaon", value: "Nagaon" },
  { label: "Nalbari", value: "Nalbari" },
  { label: "Sivasagar", value: "Sivasagar" },
  { label: "Sonitpur", value: "Sonitpur" },
  { label: "South Salmara-Mankachar", value: "South Salmara-Mankachar" },
  { label: "Tinsukia", value: "Tinsukia" },
  { label: "Udalguri", value: "Udalguri" },
  { label: "West Karbi Anglong", value: "West Karbi Anglong" },
  { label: "Araria", value: "Araria" },
  { label: "Arwal", value: "Arwal" },
  { label: "Aurangabad", value: "Aurangabad" },
  { label: "Banka", value: "Banka" },
  { label: "Begusarai", value: "Begusarai" },
  { label: "Bhagalpur", value: "Bhagalpur" },
  { label: "Bhojpur", value: "Bhojpur" },
  { label: "Buxar", value: "Buxar" },
  { label: "Darbhanga", value: "Darbhanga" },
  { label: "East Champaran", value: "East Champaran" },
  { label: "Gaya", value: "Gaya" },
  { label: "Gopalganj", value: "Gopalganj" },
  { label: "Jamui", value: "Jamui" },
  { label: "Jehanabad", value: "Jehanabad" },
  { label: "Kaimur", value: "Kaimur" },
  { label: "Katihar", value: "Katihar" },
  { label: "Khagaria", value: "Khagaria" },
  { label: "Kishanganj", value: "Kishanganj" },
  { label: "Lakhisarai", value: "Lakhisarai" },
  { label: "Madhepura", value: "Madhepura" },
  { label: "Madhubani", value: "Madhubani" },
  { label: "Munger", value: "Munger" },
  { label: "Muzaffarpur", value: "Muzaffarpur" },
  { label: "Nalanda", value: "Nalanda" },
  { label: "Nawada", value: "Nawada" },
  { label: "Patna", value: "Patna" },
  { label: "Purnia", value: "Purnia" },
  { label: "Rohtas", value: "Rohtas" },
  { label: "Saharsa", value: "Saharsa" },
  { label: "Samastipur", value: "Samastipur" },
  { label: "Saran", value: "Saran" },
  { label: "Sheikhpura", value: "Sheikhpura" },
  { label: "Sheohar", value: "Sheohar" },
  { label: "Sitamarhi", value: "Sitamarhi" },
  { label: "Siwan", value: "Siwan" },
  { label: "Supaul", value: "Supaul" },
  { label: "Vaishali", value: "Vaishali" },
  { label: "West Champaran", value: "West Champaran" },
  { label: "Balod", value: "Balod" },
  { label: "Baloda Bazar", value: "Baloda Bazar" },
  { label: "Balrampur", value: "Balrampur" },
  { label: "Bastar", value: "Bastar" },
  { label: "Bemetara", value: "Bemetara" },
  { label: "Bijapur", value: "Bijapur" },
  { label: "Bilaspur", value: "Bilaspur" },
  { label: "Dantewada", value: "Dantewada" },
  { label: "Dhamtari", value: "Dhamtari" },
  { label: "Durg", value: "Durg" },
  { label: "Gariaband", value: "Gariaband" },
  { label: "Janjgir-Champa", value: "Janjgir-Champa" },
  { label: "Jashpur", value: "Jashpur" },
  { label: "Kabirdham", value: "Kabirdham" },
  { label: "Kanker", value: "Kanker" },
  { label: "Kondagaon", value: "Kondagaon" },
  { label: "Korba", value: "Korba" },
  { label: "Koriya", value: "Koriya" },
  { label: "Mahasamund", value: "Mahasamund" },
  { label: "Mungeli", value: "Mungeli" },
  { label: "Narayanpur", value: "Narayanpur" },
  { label: "Raigarh", value: "Raigarh" },
  { label: "Raipur", value: "Raipur" },
  { label: "Rajnandgaon", value: "Rajnandgaon" },
  { label: "Sukma", value: "Sukma" },
  { label: "Surajpur", value: "Surajpur" },
  { label: "Surguja", value: "Surguja" },
  { label: "North Goa", value: "North Goa" },
  { label: "South Goa", value: "South Goa" },
  { label: "Ahmedabad", value: "Ahmedabad" },
  { label: "Amreli", value: "Amreli" },
  { label: "Anand", value: "Anand" },
  { label: "Aravalli", value: "Aravalli" },
  { label: "Banaskantha", value: "Banaskantha" },
  { label: "Bharuch", value: "Bharuch" },
  { label: "Bhavnagar", value: "Bhavnagar" },
  { label: "Botad", value: "Botad" },
  { label: "Chhota Udaipur", value: "Chhota Udaipur" },
  { label: "Dahod", value: "Dahod" },
  { label: "Dang", value: "Dang" },
  { label: "Devbhoomi Dwarka", value: "Devbhoomi Dwarka" },
  { label: "Gandhinagar", value: "Gandhinagar" },
  { label: "Gir Somnath", value: "Gir Somnath" },
  { label: "Jamnagar", value: "Jamnagar" },
  { label: "Junagadh", value: "Junagadh" },
  { label: "Kheda", value: "Kheda" },
  { label: "Kutch", value: "Kutch" },
  { label: "Mahisagar", value: "Mahisagar" },
  { label: "Mehsana", value: "Mehsana" },
  { label: "Morbi", value: "Morbi" },
  { label: "Narmada", value: "Narmada" },
  { label: "Navsari", value: "Navsari" },
  { label: "Panchmahal", value: "Panchmahal" },
  { label: "Patan", value: "Patan" },
  { label: "Porbandar", value: "Porbandar" },
  { label: "Rajkot", value: "Rajkot" },
  { label: "Sabarkantha", value: "Sabarkantha" },
  { label: "Surat", value: "Surat" },
  { label: "Surendranagar", value: "Surendranagar" },
  { label: "Tapi", value: "Tapi" },
  { label: "Vadodara", value: "Vadodara" },
  { label: "Valsad", value: "Valsad" },
  { label: "Ambala", value: "Ambala" },
  { label: "Bhiwani", value: "Bhiwani" },
  { label: "Charkhi Dadri", value: "Charkhi Dadri" },
  { label: "Faridabad", value: "Faridabad" },
  { label: "Fatehabad", value: "Fatehabad" },
  { label: "Gurugram", value: "Gurugram" },
  { label: "Hisar", value: "Hisar" },
  { label: "Jhajjar", value: "Jhajjar" },
  { label: "Jind", value: "Jind" },
  { label: "Kaithal", value: "Kaithal" },
  { label: "Karnal", value: "Karnal" },
  { label: "Kurukshetra", value: "Kurukshetra" },
  { label: "Mahendragarh", value: "Mahendragarh" },
  { label: "Nuh", value: "Nuh" },
  { label: "Palwal", value: "Palwal" },
  { label: "Panchkula", value: "Panchkula" },
  { label: "Panipat", value: "Panipat" },
  { label: "Rewari", value: "Rewari" },
  { label: "Rohtak", value: "Rohtak" },
  { label: "Sirsa", value: "Sirsa" },
  { label: "Sonipat", value: "Sonipat" },
  { label: "Yamunanagar", value: "Yamunanagar" },
  { label: "Bilaspur", value: "Bilaspur" },
  { label: "Chamba", value: "Chamba" },
  { label: "Hamirpur", value: "Hamirpur" },
  { label: "Kangra", value: "Kangra" },
  { label: "Kinnaur", value: "Kinnaur" },
  { label: "Kullu", value: "Kullu" },
  { label: "Lahaul and Spiti", value: "Lahaul and Spiti" },
  { label: "Mandi", value: "Mandi" },
  { label: "Shimla", value: "Shimla" },
  { label: "Sirmaur", value: "Sirmaur" },
  { label: "Solan", value: "Solan" },
  { label: "Una", value: "Una" },
  { label: "Bokaro", value: "Bokaro" },
  { label: "Chatra", value: "Chatra" },
  { label: "Deoghar", value: "Deoghar" },
  { label: "Dhanbad", value: "Dhanbad" },
  { label: "Dumka", value: "Dumka" },
  { label: "East Singhbhum", value: "East Singhbhum" },
  { label: "Garhwa", value: "Garhwa" },
  { label: "Giridih", value: "Giridih" },
  { label: "Godda", value: "Godda" },
  { label: "Gumla", value: "Gumla" },
  { label: "Hazaribagh", value: "Hazaribagh" },
  { label: "Jamtara", value: "Jamtara" },
  { label: "Khunti", value: "Khunti" },
  { label: "Koderma", value: "Koderma" },
  { label: "Latehar", value: "Latehar" },
  { label: "Lohardaga", value: "Lohardaga" },
  { label: "Pakur", value: "Pakur" },
  { label: "Palamu", value: "Palamu" },
  { label: "Ramgarh", value: "Ramgarh" },
  { label: "Ranchi", value: "Ranchi" },
  { label: "Sahebganj", value: "Sahebganj" },
  { label: "Seraikela Kharsawan", value: "Seraikela Kharsawan" },
  { label: "Simdega", value: "Simdega" },
  { label: "West Singhbhum", value: "West Singhbhum" },
  { label: "Bagalkot", value: "Bagalkot" },
  { label: "Ballari", value: "Ballari" },
  { label: "Belagavi", value: "Belagavi" },
  { label: "Bengaluru Rural", value: "Bengaluru Rural" },
  { label: "Bengaluru Urban", value: "Bengaluru Urban" },
  { label: "Bidar", value: "Bidar" },
  { label: "Chamarajanagar", value: "Chamarajanagar" },
  { label: "Chikkaballapur", value: "Chikkaballapur" },
  { label: "Chikkamagaluru", value: "Chikkamagaluru" },
  { label: "Chitradurga", value: "Chitradurga" },
  { label: "Dakshina Kannada", value: "Dakshina Kannada" },
  { label: "Davanagere", value: "Davanagere" },
  { label: "Dharwad", value: "Dharwad" },
  { label: "Gadag", value: "Gadag" },
  { label: "Hassan", value: "Hassan" },
  { label: "Haveri", value: "Haveri" },
  { label: "Kodagu", value: "Kodagu" },
  { label: "Kolar", value: "Kolar" },
  { label: "Koppal", value: "Koppal" },
  { label: "Mandya", value: "Mandya" },
  { label: "Mysuru", value: "Mysuru" },
  { label: "Raichur", value: "Raichur" },
  { label: "Ramanagara", value: "Ramanagara" },
  { label: "Shivamogga", value: "Shivamogga" },
  { label: "Tumakuru", value: "Tumakuru" },
  { label: "Udupi", value: "Udupi" },
  { label: "Uttara Kannada", value: "Uttara Kannada" },
  { label: "Alappuzha", value: "Alappuzha" },
  { label: "Ernakulam", value: "Ernakulam" },
  { label: "Idukki", value: "Idukki" },
  { label: "Kollam", value: "Kollam" },
  { label: "Kottayam", value: "Kottayam" },
  { label: "Kozhikode", value: "Kozhikode" },
  { label: "Malappuram", value: "Malappuram" },
  { label: "Palakkad", value: "Palakkad" },
  { label: "Pathanamthitta", value: "Pathanamthitta" },
  { label: "Thiruvananthapuram", value: "Thiruvananthapuram" },
  { label: "Wayanad", value: "Wayanad" },
  { label: "Agra", value: "Agra" },
  { label: "Aligarh", value: "Aligarh" },
  { label: "Ambedkarnagar", value: "Ambedkarnagar" },
  { label: "Amroha", value: "Amroha" },
  { label: "Auraiya", value: "Auraiya" },
  { label: "Azamgarh", value: "Azamgarh" },
  { label: "Badaun", value: "Badaun" },
  { label: "Baghpat", value: "Baghpat" },
  { label: "Bahraich", value: "Bahraich" },
  { label: "Balrampur", value: "Balrampur" },
  { label: "Banda", value: "Banda" },
  { label: "Barabanki", value: "Barabanki" },
  { label: "Bareilly", value: "Bareilly" },
  { label: "Basti", value: "Basti" },
  { label: "Bhadohi", value: "Bhadohi" },
  { label: "Bijnor", value: "Bijnor" },
  { label: "Budaun", value: "Budaun" },
  { label: "Bulandshahr", value: "Bulandshahr" },
  { label: "Chandauli", value: "Chandauli" },
  { label: "Chitrakoot", value: "Chitrakoot" },
  { label: "Deoria", value: "Deoria" },
  { label: "Etah", value: "Etah" },
  { label: "Etawah", value: "Etawah" },
  { label: "Farrukhabad", value: "Farrukhabad" },
  { label: "Fatehpur", value: "Fatehpur" },
  { label: "Firozabad", value: "Firozabad" },
  { label: "Gautam Buddha Nagar", value: "Gautam Buddha Nagar" },
  { label: "Ghaziabad", value: "Ghaziabad" },
  { label: "Ghazipur", value: "Ghazipur" },
  { label: "Gonda", value: "Gonda" },
  { label: "Hamirpur", value: "Hamirpur" },
  { label: "Hardoi", value: "Hardoi" },
  { label: "Hathras", value: "Hathras" },
  { label: "Jalaun", value: "Jalaun" },
  { label: "Jaunpur", value: "Jaunpur" },
  { label: "Jhansi", value: "Jhansi" },
  { label: "Kannauj", value: "Kannauj" },
  { label: "Kanpur Dehat", value: "Kanpur Dehat" },
  { label: "Kanpur Nagar", value: "Kanpur Nagar" },
  { label: "Kaushambi", value: "Kaushambi" },
  { label: "Kushinagar", value: "Kushinagar" },
  { label: "Lakhimpur Kheri", value: "Lakhimpur Kheri" },
  { label: "Lalitpur", value: "Lalitpur" },
  { label: "Mahoba", value: "Mahoba" },
  { label: "Mainpuri", value: "Mainpuri" },
  { label: "Mathura", value: "Mathura" },
  { label: "Meerut", value: "Meerut" },
  { label: "Mirzapur", value: "Mirzapur" },
  { label: "Muzaffarnagar", value: "Muzaffarnagar" },
  { label: "Panchsheel Nagar", value: "Panchsheel Nagar" },
  { label: "Pilibhit", value: "Pilibhit" },
  { label: "Pratapgarh", value: "Pratapgarh" },
  { label: "Raebareli", value: "Raebareli" },
  { label: "Rampur", value: "Rampur" },
  { label: "Saharanpur", value: "Saharanpur" },
  { label: "Sambhal", value: "Sambhal" },
  { label: "Sant Ravidas Nagar", value: "Sant Ravidas Nagar" },
  { label: "Shahjahanpur", value: "Shahjahanpur" },
  { label: "Shamli", value: "Shamli" },
  { label: "Shravasti", value: "Shravasti" },
  { label: "Siddharth Nagar", value: "Siddharth Nagar" },
  { label: "Sitapur", value: "Sitapur" },
  { label: "Sonbhadra", value: "Sonbhadra" },
  { label: "Sultanpur", value: "Sultanpur" },
  { label: "Unnao", value: "Unnao" },
  { label: "Varanasi", value: "Varanasi" },
  { label: "Jammu", value: "Jammu" },
  { label: "Kathua", value: "Kathua" },
  { label: "Kishtwar", value: "Kishtwar" },
  { label: "Rajouri", value: "Rajouri" },
  { label: "Ramban", value: "Ramban" },
  { label: "Reasi", value: "Reasi" },
  { label: "Samba", value: "Samba" },
  { label: "Udhampur", value: "Udhampur" },
  { label: "Doda", value: "Doda" },
  { label: "Bandipora", value: "Bandipora" },
  { label: "Baramulla", value: "Baramulla" },
  { label: "Budgam", value: "Budgam" },
  { label: "Ganderbal", value: "Ganderbal" },
  { label: "Jammu", value: "Jammu" },
  { label: "Kathua", value: "Kathua" },
  { label: "Kishtwar", value: "Kishtwar" },
  { label: "Poonch", value: "Poonch" },
  { label: "Rajouri", value: "Rajouri" },
  { label: "Ramban", value: "Ramban" },
  { label: "Reasi", value: "Reasi" },
  { label: "Samba", value: "Samba" },
  { label: "Udhampur", value: "Udhampur" },
  { label: "Bishnupur", value: "Bishnupur" },
  { label: "Chandigarh", value: "Chandigarh" },
  { label: "Churachandpur", value: "Churachandpur" },
  { label: "Imphal East", value: "Imphal East" },
  { label: "Imphal West", value: "Imphal West" },
  { label: "Senapati", value: "Senapati" },
  { label: "Tamenglong", value: "Tamenglong" },
  { label: "Thoubal", value: "Thoubal" },
  { label: "Ukhrul", value: "Ukhrul" },
  { label: "Aizawl", value: "Aizawl" },
  { label: "Champhai", value: "Champhai" },
  { label: "Lunglei", value: "Lunglei" },
  { label: "Mamit", value: "Mamit" },
  { label: "Saiha", value: "Saiha" },
  { label: "Serchhip", value: "Serchhip" },
  { label: "Dimapur", value: "Dimapur" },
  { label: "Kiphire", value: "Kiphire" },
  { label: "Longleng", value: "Longleng" },
  { label: "Mokokchung", value: "Mokokchung" },
  { label: "Mon", value: "Mon" },
  { label: "Peren", value: "Peren" },
  { label: "Phek", value: "Phek" },
  { label: "Tuensang", value: "Tuensang" },
  { label: "Wokha", value: "Wokha" },
  { label: "Zunheboto", value: "Zunheboto" },
  { label: "Bhopal", value: "Bhopal" },
  { label: "Burhanpur", value: "Burhanpur" },
  { label: "Chhindwara", value: "Chhindwara" },
  { label: "Dewas", value: "Dewas" },
  { label: "Dhar", value: "Dhar" },
  { label: "Guna", value: "Guna" },
  { label: "Gwalior", value: "Gwalior" },
  { label: "Harda", value: "Harda" },
  { label: "Hoshangabad", value: "Hoshangabad" },
  { label: "Indore", value: "Indore" },
  { label: "Jabalpur", value: "Jabalpur" },
  { label: "Katni", value: "Katni" },
  { label: "Khargone", value: "Khargone" },
  { label: "Mandla", value: "Mandla" },
  { label: "Mandsaur", value: "Mandsaur" },
  { label: "Morena", value: "Morena" },
  { label: "Nagda", value: "Nagda" },
  { label: "Narmadapuram", value: "Narmadapuram" },
  { label: "Neemuch", value: "Neemuch" },
  { label: "Panna", value: "Panna" },
  { label: "Raisen", value: "Raisen" },
  { label: "Rajgarh", value: "Rajgarh" },
  { label: "Ratlam", value: "Ratlam" },
  { label: "Sagar", value: "Sagar" },
  { label: "Satna", value: "Satna" },
  { label: "Sehore", value: "Sehore" },
  { label: "Shahdol", value: "Shahdol" },
  { label: "Shajapur", value: "Shajapur" },
  { label: "Sidhi", value: "Sidhi" },
  { label: "Singrauli", value: "Singrauli" },
  { label: "Tikamgarh", value: "Tikamgarh" },
  { label: "Ujjain", value: "Ujjain" },
  { label: "Umaria", value: "Umaria" },
  { label: "Vidhisha", value: "Vidhisha" },
  { label: "Ahmednagar", value: "Ahmednagar" },
  { label: "Akola", value: "Akola" },
  { label: "Amravati", value: "Amravati" },
  { label: "Aurangabad", value: "Aurangabad" },
  { label: "Beed", value: "Beed" },
  { label: "Bhandara", value: "Bhandara" },
  { label: "Buldhana", value: "Buldhana" },
  { label: "Chandrapur", value: "Chandrapur" },
  { label: "Dhule", value: "Dhule" },
  { label: "Gadchiroli", value: "Gadchiroli" },
  { label: "Gondia", value: "Gondia" },
  { label: "Hingoli", value: "Hingoli" },
  { label: "Jalna", value: "Jalna" },
  { label: "Jalna", value: "Jalna" },
  { label: "Kolhapur", value: "Kolhapur" },
  { label: "Latur", value: "Latur" },
  { label: "Nagpur", value: "Nagpur" },
  { label: "Nanded", value: "Nanded" },
  { label: "Nasik", value: "Nasik" },
  { label: "Osmanabad", value: "Osmanabad" },
  { label: "Parbhani", value: "Parbhani" },
  { label: "Pune", value: "Pune" },
  { label: "Raigad", value: "Raigad" },
  { label: "Ratnagiri", value: "Ratnagiri" },
  { label: "Sindhudurg", value: "Sindhudurg" },
  { label: "Solapur", value: "Solapur" },
  { label: "Thane", value: "Thane" },
  { label: "Wardha", value: "Wardha" },
  { label: "Washim", value: "Washim" },
  { label: "Yavatmal", value: "Yavatmal" },
  { label: "Bishnupur", value: "Bishnupur" },
  { label: "Imphal East", value: "Imphal East" },
  { label: "Imphal West", value: "Imphal West" },
  { label: "Senapati", value: "Senapati" },
  { label: "Tamenglong", value: "Tamenglong" },
  { label: "Thoubal", value: "Thoubal" },
  { label: "Ukhrul", value: "Ukhrul" },
  { label: "Aizawl", value: "Aizawl" },
  { label: "Champhai", value: "Champhai" },
  { label: "Lunglei", value: "Lunglei" },
  { label: "Mamit", value: "Mamit" },
  { label: "Saiha", value: "Saiha" },
  { label: "Serchhip", value: "Serchhip" },
  { label: "Dimapur", value: "Dimapur" },
  { label: "Kiphire", value: "Kiphire" },
  { label: "Longleng", value: "Longleng" },
  { label: "Mokokchung", value: "Mokokchung" },
  { label: "Mon", value: "Mon" },
  { label: "Peren", value: "Peren" },
  { label: "Phek", value: "Phek" },
  { label: "Tuensang", value: "Tuensang" },
  { label: "Wokha", value: "Wokha" },
  { label: "Zunheboto", value: "Zunheboto" },
];
