export const cityOptions = [
  { label: "Mumbai", value: "mumbai" },
  { label: "New Delhi", value: "new_delhi" },
  { label: "Bangalore", value: "bangalore" },
  { label: "Chennai", value: "chennai" },
  { label: "Kolkata", value: "kolkata" },
  { label: "Hyderabad", value: "hyderabad" },
  { label: "Ahmedabad", value: "ahmedabad" },
  { label: "Jaipur", value: "jaipur" },
  { label: "Pune", value: "pune" },
  { label: "Surat", value: "surat" },
  { label: "Lucknow", value: "lucknow" },
  { label: "Kanpur", value: "kanpur" },
  { label: "Nagpur", value: "nagpur" },
  { label: "Indore", value: "indore" },
  { label: "Chandigarh", value: "chandigarh" },
  { label: "Bhopal", value: "bhopal" },
  { label: "Coimbatore", value: "coimbatore" },
  { label: "Vadodara", value: "vadodara" },
  { label: "Patna", value: "patna" },
  { label: "Visakhapatnam", value: "visakhapatnam" },
];
