export const countryOptions = [
  { label: "India", value: "india" },
  { label: "United States", value: "united_states" },
  { label: "China", value: "china" },
  { label: "Japan", value: "japan" },
  { label: "Germany", value: "germany" },
  { label: "France", value: "france" },
  { label: "United Kingdom", value: "united_kingdom" },
  { label: "Canada", value: "canada" },
  { label: "Australia", value: "australia" },
  { label: "Brazil", value: "brazil" },
  { label: "South Africa", value: "south_africa" },
  { label: "Russia", value: "russia" },
  { label: "Italy", value: "italy" },
  { label: "Mexico", value: "mexico" },
  { label: "Spain", value: "spain" },
  { label: "South Korea", value: "south_korea" },
  { label: "Saudi Arabia", value: "saudi_arabia" },
  { label: "Argentina", value: "argentina" },
  { label: "Turkey", value: "turkey" },
  { label: "Indonesia", value: "indonesia" },
];
