export const stateOptions = [
  { label: "Maharashtra", value: "maharashtra" },
  { label: "Delhi", value: "delhi" },
  { label: "Karnataka", value: "karnataka" },
  { label: "Tamil Nadu", value: "tamil_nadu" },
  { label: "West Bengal", value: "west_bengal" },
  { label: "Telangana", value: "telangana" },
  { label: "Gujarat", value: "gujarat" },
  { label: "Rajasthan", value: "rajasthan" },
  { label: "Uttar Pradesh", value: "uttar_pradesh" },
  { label: "Madhya Pradesh", value: "madhya_pradesh" },
  { label: "Chandigarh", value: "chandigarh" },
  { label: "Bihar", value: "bihar" },
  { label: "Andhra Pradesh", value: "andhra_pradesh" },
  { label: "Kerala", value: "kerala" },
  { label: "Jharkhand", value: "jharkhand" },
  { label: "Odisha", value: "odisha" },
  { label: "Haryana", value: "haryana" },
  { label: "Himachal Pradesh", value: "himachal_pradesh" },
  { label: "Sikkim", value: "sikkim" },
  { label: "Meghalaya", value: "meghalaya" },
];
